/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diegomolinayvictorvalladares_lab9;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Random;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author diego
 */
public class login extends javax.swing.JFrame {
    Random r = new Random();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        administrarExamenes aE = new administrarExamenes("./Examenes.cbm");
        aE.cargarArchivo();
        cargarMaestros();
        cargarAlumnos();
    }
    public void cargarMaestros(){
        Dba db = new Dba("./Universidad.accdb");
        db.conectar();
        try {
            db.query.execute("select Nombre,RRHH,Usuario,Password from Maestros");
            ResultSet rs = db.query.getResultSet();           
            while (rs.next()) {
                maestros.add(new Maestro(rs.getInt(2), rs.getString(1), rs.getString(3), rs.getString(4)));
            }            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }
    
    public void cargarAlumnos(){
        Dba db = new Dba("./Universidad.accdb");
        db.conectar();
        try {
            db.query.execute("select Nombre,NumCuenta,Carrera,Usuario,Password from Alumnos");
            ResultSet rs = db.query.getResultSet();           
            while (rs.next()) {
                alumnos.add(new Alumno(rs.getInt(2), rs.getString(3), rs.getString(1), rs.getString(4), rs.getString(5)));
            }            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro_maestro = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bt_registrarse_maestro = new javax.swing.JButton();
        tf_nombre_maestro = new javax.swing.JTextField();
        tf_user_maestro = new javax.swing.JTextField();
        tf_password_maestro = new javax.swing.JTextField();
        tf_rrhh = new javax.swing.JTextField();
        pf_password_maestro = new javax.swing.JPasswordField();
        registro_alumno = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_nombre_alumno = new javax.swing.JTextField();
        bt_registro_alumno = new javax.swing.JButton();
        tf_user_alumno = new javax.swing.JTextField();
        tf_password_alumno = new javax.swing.JTextField();
        pf_password_alumno = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        tf_carrera_alumno = new javax.swing.JTextField();
        plataforma_alumno = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        label_nombre_alumno = new javax.swing.JLabel();
        label_cronometro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb_clases = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        F1 = new javax.swing.JRadioButton();
        V1 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_q1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label_q2 = new javax.swing.JLabel();
        label_q3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        label_q4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        label_q5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        V2 = new javax.swing.JRadioButton();
        F2 = new javax.swing.JRadioButton();
        V3 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        V4 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        V5 = new javax.swing.JRadioButton();
        F5 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        plataforma_maestro = new javax.swing.JFrame();
        plataforma_admin = new javax.swing.JFrame();
        bt_crudExamen = new javax.swing.JButton();
        bt_crudClase = new javax.swing.JButton();
        bt_verClases = new javax.swing.JButton();
        bt_crudPregunta = new javax.swing.JButton();
        bt_Calificaciones = new javax.swing.JButton();
        jd_crearExamen = new javax.swing.JDialog();
        cb_idClases = new javax.swing.JComboBox<>();
        bt_crearExamen = new javax.swing.JButton();
        jd_verClases = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_clases = new javax.swing.JTable();
        cb_verClases = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_password = new javax.swing.JTextField();
        bt_registro_m = new javax.swing.JButton();
        bt_login = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        registro_maestro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Registrarse como maestro");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Confirmar Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("RRHH");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre de usuario");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        bt_registrarse_maestro.setText("Registrarse");
        bt_registrarse_maestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarse_maestroMouseClicked(evt);
            }
        });
        jPanel2.add(bt_registrarse_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));
        jPanel2.add(tf_nombre_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, -1));
        jPanel2.add(tf_user_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, -1));
        jPanel2.add(tf_password_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));
        jPanel2.add(tf_rrhh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, -1));
        jPanel2.add(pf_password_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, -1));

        registro_maestro.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        registro_alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Registrarse como alumno");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Confirmar Contraseña");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre de usuario");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contraseña");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Carrera");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        jPanel3.add(tf_nombre_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        bt_registro_alumno.setText("Registrarse");
        bt_registro_alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registro_alumnoMouseClicked(evt);
            }
        });
        jPanel3.add(bt_registro_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, 40));
        jPanel3.add(tf_user_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));
        jPanel3.add(tf_password_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, -1));
        jPanel3.add(pf_password_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nombre");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        jPanel3.add(tf_carrera_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));

        registro_alumno.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 400));

        plataforma_alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombre_alumno.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        label_nombre_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(label_nombre_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 200, 30));

        label_cronometro.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        label_cronometro.setForeground(new java.awt.Color(0, 0, 0));
        label_cronometro.setText("0:00 minutos");
        jPanel4.add(label_cronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jButton1.setText("Modificar");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("1.-");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("2.-");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("3.-");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("4.-");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("5.-");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Clase");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jPanel4.add(cb_clases, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 190, -1));

        jButton2.setText("Empezar examen");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Bienvenido: ");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        F1.setForeground(new java.awt.Color(0, 0, 0));
        F1.setText("F");
        jPanel4.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        V1.setForeground(new java.awt.Color(0, 0, 0));
        V1.setText("V");
        jPanel4.add(V1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 380, 20));
        jPanel4.add(label_q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 380, 30));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 380, 20));
        jPanel4.add(label_q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 380, 20));
        jPanel4.add(label_q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 380, 20));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 380, 20));
        jPanel4.add(label_q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 380, 20));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 380, 20));
        jPanel4.add(label_q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 380, 20));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 380, 20));

        V2.setForeground(new java.awt.Color(0, 0, 0));
        V2.setText("V");
        jPanel4.add(V2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        F2.setForeground(new java.awt.Color(0, 0, 0));
        F2.setText("F");
        jPanel4.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        V3.setForeground(new java.awt.Color(0, 0, 0));
        V3.setText("V");
        jPanel4.add(V3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        F3.setForeground(new java.awt.Color(0, 0, 0));
        F3.setText("F");
        jPanel4.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        V4.setForeground(new java.awt.Color(0, 0, 0));
        V4.setText("V");
        jPanel4.add(V4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        F4.setForeground(new java.awt.Color(0, 0, 0));
        F4.setText("F");
        jPanel4.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        V5.setForeground(new java.awt.Color(0, 0, 0));
        V5.setText("V");
        jPanel4.add(V5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        F5.setForeground(new java.awt.Color(0, 0, 0));
        F5.setText("F");
        jPanel4.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jButton5.setText("Finalizar examen");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 210, -1));

        jButton6.setText("Agregar Clase");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 150, 30));

        plataforma_alumno.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        javax.swing.GroupLayout plataforma_maestroLayout = new javax.swing.GroupLayout(plataforma_maestro.getContentPane());
        plataforma_maestro.getContentPane().setLayout(plataforma_maestroLayout);
        plataforma_maestroLayout.setHorizontalGroup(
            plataforma_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        plataforma_maestroLayout.setVerticalGroup(
            plataforma_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        plataforma_admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_crudExamen.setText("Crear Examen");
        bt_crudExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crudExamenActionPerformed(evt);
            }
        });
        plataforma_admin.getContentPane().add(bt_crudExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 270, 40));

        bt_crudClase.setText("Crear Clase");
        bt_crudClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crudClaseActionPerformed(evt);
            }
        });
        plataforma_admin.getContentPane().add(bt_crudClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 270, 50));

        bt_verClases.setText("Ver Clases");
        bt_verClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verClasesActionPerformed(evt);
            }
        });
        plataforma_admin.getContentPane().add(bt_verClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 270, 60));

        bt_crudPregunta.setText("Crear Pregunta");
        plataforma_admin.getContentPane().add(bt_crudPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 270, 50));

        bt_Calificaciones.setText("Ir a Centro de Calificaciones");
        plataforma_admin.getContentPane().add(bt_Calificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 260, 50));

        bt_crearExamen.setText("Crear Examen");
        bt_crearExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearExamenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_crearExamenLayout = new javax.swing.GroupLayout(jd_crearExamen.getContentPane());
        jd_crearExamen.getContentPane().setLayout(jd_crearExamenLayout);
        jd_crearExamenLayout.setHorizontalGroup(
            jd_crearExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearExamenLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jd_crearExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_idClases, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_crearExamen, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jd_crearExamenLayout.setVerticalGroup(
            jd_crearExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearExamenLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(cb_idClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(bt_crearExamen)
                .addGap(87, 87, 87))
        );

        jt_clases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Examen", "Cant Preguntas"
            }
        ));
        jScrollPane1.setViewportView(jt_clases);

        cb_verClases.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_verClasesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jd_verClasesLayout = new javax.swing.GroupLayout(jd_verClases.getContentPane());
        jd_verClases.getContentPane().setLayout(jd_verClasesLayout);
        jd_verClasesLayout.setHorizontalGroup(
            jd_verClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_verClasesLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_verClasesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_verClases, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jd_verClasesLayout.setVerticalGroup(
            jd_verClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_verClasesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cb_verClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NeoBlackboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        Contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña.setText("Contraseña");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 246, -1));
        jPanel1.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 246, -1));

        bt_registro_m.setText("Registrarse como Maestro");
        bt_registro_m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registro_mMouseClicked(evt);
            }
        });
        jPanel1.add(bt_registro_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 60));

        bt_login.setText("Iniciar Sesion");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        jPanel1.add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 160, 40));

        jButton3.setText("Registrarse como Alumno");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registro_mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registro_mMouseClicked
        this.setVisible(false);
        registro_maestro.pack();
        registro_maestro.setLocationRelativeTo(this);
        registro_maestro.setVisible(true);
    }//GEN-LAST:event_bt_registro_mMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        this.setVisible(false);
        registro_alumno.pack();
        registro_alumno.setLocationRelativeTo(this);
        registro_alumno.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void bt_registrarse_maestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarse_maestroMouseClicked
        String nombre;
        String user;
        String Password;
        String confirm;
        int rrhh;
        
        try{
            nombre = tf_nombre_maestro.getText();
            user = tf_user_maestro.getText();
            Password = tf_password_maestro.getText();
            confirm = pf_password_maestro.getText();
            rrhh = Integer.parseInt(tf_rrhh.getText());
            if (!(confirm.equals(Password))){
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }else{
                Maestro x = new Maestro (rrhh, nombre, user, Password);
                maestros.add(x);
                
                Dba db = new Dba("./Universidad.accdb");
                db.conectar();
                
                db.query.execute("INSERT INTO Maestros"
                    + " (Nombre,RRHH)"
                    + " VALUES ('" + nombre + "', '" + rrhh + "')");
                db.commit();
                
                JOptionPane.showMessageDialog(null, "Se ha creado el maestro exitosamente");
                db.desconectar();
                
                tf_nombre_maestro.setText("");
                tf_user_maestro.setText("");
                tf_password_maestro.setText("");
                pf_password_maestro.setText("");
                
                registro_maestro.setVisible(false);
                this.pack();
                this.setLocationRelativeTo(null);
                this.setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
        this.setVisible(true);
    }//GEN-LAST:event_bt_registrarse_maestroMouseClicked

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        String user, pass;
        user = tf_username.getText();
        pass = tf_password.getText();
        boolean entraA = false;
        boolean entraM = false;
        if(user.equals(username_admin) && pass.equals(password_admin)){
            plataforma_admin.setVisible(true);
        }
        else{
            for (Alumno alumno : alumnos) {
                if(alumno.getUser().equals(user) && alumno.getPass().equals(pass)){
                    entraA = true;
                    break;
                }
            }
            if(entraA==false){
                for (Maestro maestro : maestros) {
                    if(maestro.getUser().equals(user) && maestro.getPass().equals(pass)){
                        entraM = true;
                        break;
                    }
                }
                if(entraM ==true){
                    plataforma_maestro.setVisible(true);
                }
            }
            else if(entraA==true){
                plataforma_alumno.setVisible(true);
            }
            else if(entraA == false && entraM == false){
                JOptionPane.showMessageDialog(null, "Usuario y/o contrasena incorrecta");
            }
        }
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_registro_alumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registro_alumnoMouseClicked
        // TODO add your handling code here:
        String nombre, user, pass, confirm, carrera;
        nombre = tf_nombre_alumno.getText();
        user = tf_user_alumno.getText();
        pass = tf_password_alumno.getText();
        confirm = pf_password_alumno.getText();
        carrera = tf_carrera_alumno.getText();
        int numCuenta = 1+r.nextInt(999999);
        if(pass.equals(confirm)){
            Alumno x = new Alumno(numCuenta, carrera, nombre, user, pass);
            alumnos.add(x);
            Dba db = new Dba("./Universidad.accdb");
            db.conectar();
            try {
                db.query.execute("INSERT INTO Alumnos"
                        + " (Nombre,NumCuenta,Carrera)"
                        + " VALUES ('" + nombre + "', '" + numCuenta + "', '" + nombre + "')");
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            db.commit();
            JOptionPane.showMessageDialog(null, "Se ha registrado exitosamente");
            db.desconectar();
            tf_nombre_alumno.setText("");
            tf_user_alumno.setText("");
            tf_password_alumno.setText("");
            pf_password_alumno.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Las contrasenas no coinciden");
        }
        this.setVisible(true);
    }//GEN-LAST:event_bt_registro_alumnoMouseClicked

    private void bt_crudClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crudClaseActionPerformed
        // TODO add your handling code here:
        String nomClase = JOptionPane.showInputDialog(null, "Nombre de la Clase");
        int idClase = Integer.parseInt(JOptionPane.showInputDialog("ID de la Clase"));
        Clase c = new Clase(nomClase, idClase);
        clases.add(c);
        Dba db = new Dba("./Universidad.accdb");
            db.conectar();
            try {
                db.query.execute("INSERT INTO Clases"
                        + " (Nombre,IDclase)"
                        + " VALUES ('" + nomClase + "', '" + idClase + "')");
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            db.commit();
            JOptionPane.showMessageDialog(null, "Se ha creado exitosamente");
    }//GEN-LAST:event_bt_crudClaseActionPerformed

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_loginMouseClicked

    private void bt_crudExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crudExamenActionPerformed
        // TODO add your handling code here:
        jd_crearExamen.setVisible(true);
        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_idClases.getModel();
        dc.removeAllElements();
        for (Clase clase : clases) {
            dc.addElement(clase);
        }
        cb_idClases.setModel(dc);
    }//GEN-LAST:event_bt_crudExamenActionPerformed

    private void bt_crearExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearExamenActionPerformed
        // TODO add your handling code here:
        Clase c = (Clase)cb_idClases.getSelectedItem();
        int idC = c.getIdClase();
        Examen e = new Examen(idC);
        administrarExamenes aE = new administrarExamenes("./Examenes.cbm");
        aE.cargarArchivo();
        aE.setExamen(e);
        aE.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Examen guardado exitosamente");
    }//GEN-LAST:event_bt_crearExamenActionPerformed

    private void bt_verClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verClasesActionPerformed
        // TODO add your handling code here:
        jd_verClases.pack();
        jd_verClases.setVisible(true);
        jt_clases.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Examen 1", "Examen 2"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        DefaultComboBoxModel dc = (DefaultComboBoxModel) cb_verClases.getModel();
        dc.removeAllElements();
        for (Clase clase : clases) {
            dc.addElement(clase);
        }
        cb_verClases.setModel(dc);
    }//GEN-LAST:event_bt_verClasesActionPerformed

    private void cb_verClasesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_verClasesItemStateChanged
        // TODO add your handling code here:
        Clase c = (Clase)cb_verClases.getSelectedItem();
        DefaultTableModel m = (DefaultTableModel) jt_clases.getModel();
        m.setRowCount(0);
        Object row[] = {c.getIdEx1(), 5};
        m.addRow(row);
        Object row2[] = {c.getIdEx2(), 5};
        m.addRow(row2);
        jt_clases.setModel(m);
    }//GEN-LAST:event_cb_verClasesItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        cronometro = new Cronometro (label_cronometro);
        Thread proceso1 = new Thread (cronometro);
        proceso1.start();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // cronometro.setVive(false);
        cronometro.setAvanzar(false);
        JOptionPane.showMessageDialog(null, "Ha terminado el examen!!");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked

    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JRadioButton F1;
    private javax.swing.JRadioButton F2;
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton F5;
    private javax.swing.JRadioButton V1;
    private javax.swing.JRadioButton V2;
    private javax.swing.JRadioButton V3;
    private javax.swing.JRadioButton V4;
    private javax.swing.JRadioButton V5;
    private javax.swing.JButton bt_Calificaciones;
    private javax.swing.JButton bt_crearExamen;
    private javax.swing.JButton bt_crudClase;
    private javax.swing.JButton bt_crudExamen;
    private javax.swing.JButton bt_crudPregunta;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_registrarse_maestro;
    private javax.swing.JButton bt_registro_alumno;
    private javax.swing.JButton bt_registro_m;
    private javax.swing.JButton bt_verClases;
    private javax.swing.JComboBox<String> cb_clases;
    private javax.swing.JComboBox<String> cb_idClases;
    private javax.swing.JComboBox<String> cb_verClases;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JDialog jd_crearExamen;
    private javax.swing.JDialog jd_verClases;
    private javax.swing.JTable jt_clases;
    private javax.swing.JLabel label_cronometro;
    private javax.swing.JLabel label_nombre_alumno;
    private javax.swing.JLabel label_q1;
    private javax.swing.JLabel label_q2;
    private javax.swing.JLabel label_q3;
    private javax.swing.JLabel label_q4;
    private javax.swing.JLabel label_q5;
    private javax.swing.JPasswordField pf_password_alumno;
    private javax.swing.JPasswordField pf_password_maestro;
    private javax.swing.JFrame plataforma_admin;
    private javax.swing.JFrame plataforma_alumno;
    private javax.swing.JFrame plataforma_maestro;
    private javax.swing.JFrame registro_alumno;
    private javax.swing.JFrame registro_maestro;
    private javax.swing.JTextField tf_carrera_alumno;
    private javax.swing.JTextField tf_nombre_alumno;
    private javax.swing.JTextField tf_nombre_maestro;
    private javax.swing.JTextField tf_password;
    private javax.swing.JTextField tf_password_alumno;
    private javax.swing.JTextField tf_password_maestro;
    private javax.swing.JTextField tf_rrhh;
    private javax.swing.JTextField tf_user_alumno;
    private javax.swing.JTextField tf_user_maestro;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
    String username_admin = "admin";
    String password_admin = "admin1234";
    ArrayList <Alumno> alumnos = new ArrayList ();
    ArrayList <Maestro> maestros = new ArrayList ();
    ArrayList<Clase> clases = new ArrayList();
    Cronometro cronometro;
}
