/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diegomolinayvictorvalladares_lab9;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro_maestro = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bt_registrarse_maestro = new javax.swing.JButton();
        tf_nombre_maestro = new javax.swing.JTextField();
        tf_user_maestro = new javax.swing.JTextField();
        tf_password_maestro = new javax.swing.JTextField();
        tf_rrhh = new javax.swing.JTextField();
        pf_password_maestro = new javax.swing.JPasswordField();
        registro_alumno = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_nombre_cliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tf_user_alumno = new javax.swing.JTextField();
        tf_password_alumno = new javax.swing.JTextField();
        pf_password_alumno = new javax.swing.JPasswordField();
        plataforma_alumno = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        label_nombre_alumno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        plataforma_maestro = new javax.swing.JFrame();
        plataforma_admin = new javax.swing.JFrame();
        bt_crudExamen = new javax.swing.JButton();
        bt_crudClase = new javax.swing.JButton();
        bt_verClases = new javax.swing.JButton();
        bt_crudPregunta = new javax.swing.JButton();
        bt_Calificaciones = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_password = new javax.swing.JTextField();
        bt_registro_m = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        registro_maestro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Registrarse como maestro");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Confirmar Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("RRHH");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre de usuario");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        bt_registrarse_maestro.setText("Registrarse");
        bt_registrarse_maestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarse_maestroMouseClicked(evt);
            }
        });
        jPanel2.add(bt_registrarse_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));
        jPanel2.add(tf_nombre_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, -1));
        jPanel2.add(tf_user_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, -1));
        jPanel2.add(tf_password_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, -1));
        jPanel2.add(tf_rrhh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 190, -1));
        jPanel2.add(pf_password_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, -1));

        registro_maestro.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        registro_alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Registrarse como alumno");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Confirmar Contraseña");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre de usuario");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contraseña");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        jPanel3.add(tf_nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        jButton1.setText("Registrarse");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, 40));
        jPanel3.add(tf_user_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));
        jPanel3.add(tf_password_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, -1));
        jPanel3.add(pf_password_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        registro_alumno.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        plataforma_alumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombre_alumno.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        label_nombre_alumno.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(label_nombre_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 200, 30));

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Bienvenido: ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        plataforma_alumno.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        javax.swing.GroupLayout plataforma_maestroLayout = new javax.swing.GroupLayout(plataforma_maestro.getContentPane());
        plataforma_maestro.getContentPane().setLayout(plataforma_maestroLayout);
        plataforma_maestroLayout.setHorizontalGroup(
            plataforma_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        plataforma_maestroLayout.setVerticalGroup(
            plataforma_maestroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        plataforma_admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_crudExamen.setText("Crear Examen");
        plataforma_admin.getContentPane().add(bt_crudExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 270, 40));

        bt_crudClase.setText("Crear Clase");
        plataforma_admin.getContentPane().add(bt_crudClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 270, 50));

        bt_verClases.setText("Ver Clases");
        plataforma_admin.getContentPane().add(bt_verClases, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 270, 60));

        bt_crudPregunta.setText("Crear Pregunta");
        plataforma_admin.getContentPane().add(bt_crudPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 270, 50));

        bt_Calificaciones.setText("Ir a Centro de Calificaciones");
        plataforma_admin.getContentPane().add(bt_Calificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 260, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NeoBlackboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        Contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña.setText("Contraseña");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jPanel1.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 246, -1));
        jPanel1.add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 246, -1));

        bt_registro_m.setText("Registrarse como Maestro");
        bt_registro_m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registro_mMouseClicked(evt);
            }
        });
        jPanel1.add(bt_registro_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 200, 60));

        jButton2.setText("Iniciar Sesion");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 160, 40));

        jButton3.setText("Registrarse como Alumno");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registro_mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registro_mMouseClicked
        this.setVisible(false);
        registro_maestro.pack();
        registro_maestro.setLocationRelativeTo(this);
        registro_maestro.setVisible(true);
    }//GEN-LAST:event_bt_registro_mMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        this.setVisible(false);
        registro_alumno.pack();
        registro_alumno.setLocationRelativeTo(this);
        registro_alumno.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_registrarse_maestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarse_maestroMouseClicked
        String nombre;
        String user;
        String Password;
        String confirm;
        int rrhh;
        
        try{
            nombre = tf_nombre_maestro.getText();
            user = tf_user_maestro.getText();
            Password = tf_password_maestro.getText();
            confirm = pf_password_maestro.getText();
            rrhh = Integer.parseInt(tf_rrhh.getText());
            if (!(confirm.equals(Password))){
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
            }else{
                Maestro x = new Maestro (rrhh, nombre, user, Password);
                maestros.add(x);
                
                Dba db = new Dba("./Universidad.accdb");
                db.conectar();
                
                db.query.execute("INSERT INTO Maestros"
                    + " (Nombre,RRHH)"
                    + " VALUES ('" + nombre + "', '" + rrhh + "')");
                db.commit();
                
                JOptionPane.showMessageDialog(null, "Se ha creado el maestro exitosamente");
                db.desconectar();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }//GEN-LAST:event_bt_registrarse_maestroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JButton bt_Calificaciones;
    private javax.swing.JButton bt_crudClase;
    private javax.swing.JButton bt_crudExamen;
    private javax.swing.JButton bt_crudPregunta;
    private javax.swing.JButton bt_registrarse_maestro;
    private javax.swing.JButton bt_registro_m;
    private javax.swing.JButton bt_verClases;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label_nombre_alumno;
    private javax.swing.JPasswordField pf_password_alumno;
    private javax.swing.JPasswordField pf_password_maestro;
    private javax.swing.JFrame plataforma_admin;
    private javax.swing.JFrame plataforma_alumno;
    private javax.swing.JFrame plataforma_maestro;
    private javax.swing.JFrame registro_alumno;
    private javax.swing.JFrame registro_maestro;
    private javax.swing.JTextField tf_nombre_cliente;
    private javax.swing.JTextField tf_nombre_maestro;
    private javax.swing.JTextField tf_password;
    private javax.swing.JTextField tf_password_alumno;
    private javax.swing.JTextField tf_password_maestro;
    private javax.swing.JTextField tf_rrhh;
    private javax.swing.JTextField tf_user_alumno;
    private javax.swing.JTextField tf_user_maestro;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
    String username_admin = "admin";
    String password_admin = "admin1234";
    ArrayList <Alumno> alumnos = new ArrayList ();
    ArrayList <Maestro> maestros = new ArrayList ();
}
